---
- name: user
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: Reboot
          shell: reboot
          async: 1000
          poll: 0
      become: true
# launching
# > ansible-playbook -i hosts.ini user.yml
